version: "3.5"

services:

  database:
    image: mariadb:latest
    restart: always
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
    ports:
      - "3306:3306"
    env_file:
      - ./.env

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
